import Head from 'next/head'

import Menu from '../components/menu'
import styles from '../styles/Home.module.css'

export default function Contatos() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Além do livro</title>
        <meta name="description" content="Generated by create next app" />
   <link rel="icon"href="image/mundo.png"/>
      </Head>
			<Menu />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Deseja saber mais de nossos livros?        
				</h1><p></p>
        <h2>Entre em contato conosco</h2> 
      </main>
      <footer className={styles.footer}>
    
      </footer>
    </div>
  )