import Head from 'next/head'


import Menu from '../components/menu'
import styles from '../styles/Home.module.css'
import CardLivro from "../components/cardLivro"
import api from "./api/api"

export default function Login({livro}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Menu />
      <main className={styles.main}>
        {
        livro.map(livro => {
          return(
            <div key={livro.id}>
              <CardLivro nome={livro.nome} titulo={livro.titulo} editora={livro.editora} data_publicacao={livro.data_publicacao} preco={livro.preco}id={livro.id}/>
            </div>
          )
        })
        }
</main>
</div>
  )
}

export async function getServerSideProps(){
  const response = await api.get("/livros");
  const livro = response.data;

  return {
    props:{
      livro
    }
  }
}